
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://wjvevhghmwyiwyemhkbe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndqdmV2aGdobXd5aXd5ZW1oa2JlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxMDI3NzAsImV4cCI6MjA2MDY3ODc3MH0.GzkIcSiWzjJPnEomY3XZkygcxm2Bvq7Poz57O02mzN4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
